services:
    _defaults:
        bind:
            PoP\Hooks\HooksAPIInterface: '@hooks_api'
            PoP\Translation\TranslationAPIInterface: '@translation_api'

    PoP\TranslateDirective\Conditional\UserState\Conditional\UserRoles\Hooks\:
        resource: '../../../../../src/Conditional/UserState/Conditional/UserRoles/Hooks/*'
        public: true

    PoP\TranslateDirective\Conditional\UserState\Conditional\UserRoles\TypeResolverDecorators\:
        resource: '../../../../../src/Conditional/UserState/Conditional/UserRoles/TypeResolverDecorators/*'
        public: true
