services:
    _defaults:
        bind:
            PoP\Hooks\HooksAPIInterface: '@hooks_api'
            PoP\Translation\TranslationAPIInterface: '@translation_api'

    PoP\TranslateDirective\Conditional\UserState\Hooks\:
        resource: '../../../src/Conditional/UserState/Hooks/*'
        public: true

    PoP\TranslateDirective\Conditional\UserState\TypeResolverDecorators\:
        resource: '../../../src/Conditional/UserState/TypeResolverDecorators/*'
        public: true
